language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - wget http://phpdox.de/releases/phpdox.phar
    - composer self-update
    - composer install

script: phpunit

after_script: php phpdox.phar